// <auto-generated />
using System;
using AndrewStoddardVacationPlanner.Models.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AndrewStoddardVacationPlanner.Migrations
{
    [DbContext(typeof(VacationContext))]
    partial class VacationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "6.0.0-preview.1.21102.2")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ActivityTrip", b =>
                {
                    b.Property<int>("ActivitiesId")
                        .HasColumnType("int");

                    b.Property<int>("TripsId")
                        .HasColumnType("int");

                    b.HasKey("ActivitiesId", "TripsId");

                    b.HasIndex("TripsId");

                    b.ToTable("ActivityTrip");
                });

            modelBuilder.Entity("AndrewStoddardVacationPlanner.Models.DomainModels.Accommodation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accommodations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "book@highrise.com",
                            Name = "High-Rise Condo",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Email = "book@lowrise.com",
                            Name = "Low-Rise Condo",
                            PhoneNumber = "0987654321"
                        },
                        new
                        {
                            Id = 3,
                            Email = "book@motel8.com",
                            Name = "Motel 8",
                            PhoneNumber = "5632147890"
                        },
                        new
                        {
                            Id = 4,
                            Email = "book@holidayinn.com",
                            Name = "Holiday Inn",
                            PhoneNumber = "5823694170"
                        });
                });

            modelBuilder.Entity("AndrewStoddardVacationPlanner.Models.DomainModels.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SkyDiving"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Parasail"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Go Karts"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mini Golf"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mountain Hiking"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Deep Sea Fishing"
                        });
                });

            modelBuilder.Entity("AndrewStoddardVacationPlanner.Models.DomainModels.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Orlando, Florida"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Panama City, Florida"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Orange Beach, Alabama"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Helen, Georgia"
                        },
                        new
                        {
                            Id = 5,
                            Name = "New York City, New York"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Gatlinburg, Tennessee"
                        });
                });

            modelBuilder.Entity("AndrewStoddardVacationPlanner.Models.DomainModels.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccommodationId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccommodationId = 4,
                            DestinationId = 6,
                            EndDate = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2019, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AccommodationId = 1,
                            DestinationId = 2,
                            EndDate = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2020, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ActivityTrip", b =>
                {
                    b.HasOne("AndrewStoddardVacationPlanner.Models.DomainModels.Activity", null)
                        .WithMany()
                        .HasForeignKey("ActivitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AndrewStoddardVacationPlanner.Models.DomainModels.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AndrewStoddardVacationPlanner.Models.DomainModels.Trip", b =>
                {
                    b.HasOne("AndrewStoddardVacationPlanner.Models.DomainModels.Accommodation", "Accommodation")
                        .WithMany()
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AndrewStoddardVacationPlanner.Models.DomainModels.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");

                    b.Navigation("Destination");
                });
#pragma warning restore 612, 618
        }
    }
}
